baseURL = "https://objective-boyd-9b8f29.netlify.com"
title = "five-dots blog"
theme = "hugo-theme-even"

languageCode = "en"
defaultContentLanguage = "en"
hasCJKLanguage = true

preserveTaxonomyNames = true
enableRobotsTXT = true
enableEmoji = true
paginate = 10

# Syntax highlighting by Chroma. NOTE: Don't enable `highlightInClient` and `chroma` at the same time!
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsOptions = "linenos=table"
pygmentsCodefencesGuessSyntax = true

enableGitInfo = false
disqusShortname = ""
googleAnalytics = "UA-141603232-1"
copyright = ""

[permalinks]
  post = "/:year/:month/:filename/"

[author]
  name = "five-dots"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

# [[menu.main]]
#   name = "R Packages"
#   weight = 20
#   identifier = "r-packages"
#   url = "/series/r-packages/"

# [[menu.main]]
#   name = "Archives"
#   weight = 30
#   identifier = "archives"
#   url = "/post/"

[[menu.main]]
  name = "Categories"
  weight = 50
  identifier = "categories"
  url = "/categories/"

[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"

[params]
  # Used to give a friendly message when you have an incompatible update
  version = "4.x"

  # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  debug = false

  # Site creation time
  since = "2019"

  # use public git repo url to link lastmod git commit, enableGitInfo should be true.
  gitRepo = ""

  # site info (optional)
  # default: the title value
  logoTitle = "five-dots blog"
  keywords = ["programming", "R", "statistics", "emacs", "finance", "trading"]
  description = "five-dots blog"

  # paginate of archives, tags and categories
  archivePaginate = 10

  # show 'xx Posts In Total' in archive page ?
  showArchiveCount = false

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  # dateFormatToUse = "2006-01-02"
  dateFormatToUse = "Jan2, 2006"

  # show word count and read time ?
  moreMeta = false

  # Syntax highlighting by highlight.js
  highlightInClient = false

  # Some global options, you can also close or open something in front matter for a single post,
  # see more information from `archetypes/default.md`.
  toc = false

  # Auto expand and collapse toc
  autoCollapseToc = false

  # see https://github.com/fancyapps/fancybox
  fancybox = true

  # mathjax
  # see https://www.mathjax.org/
  mathjax = true
  mathjaxEnableSingleDollar = true
  mathjaxEnableAutoNumber = false
  # You should install mathjax in `your-site/static/lib/mathjax`
  mathjaxUseLocalFiles = false

  # contain author, lastMod, markdown link, license
  postMetaInFooter = false

  # Only effective when hugo will output .md files.
  linkToMarkDown = false
  # e.g. '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'
  contentCopyright = ''

  # Changyan app id
  changyanAppid = ""
  # Changyan app key
  changyanAppkey = ""

  # LiveRe UID
  livereUID = ""

  # baidu push
  baiduPush = false
  # Baidu Analytics
  baiduAnalytics = ""
  # Baidu Verification
  baiduVerification = ""

  # Google Verification
  googleVerification = ""

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
	customCSS = ["custom.css"]
  customJS = []

  # please keep same with uglyurls setting
  uglyURLs = false

  # load these files from public cdn
  [params.publicCDN]
    enable = true
    jquery = '<script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>'
    slideout = '<script src="https://cdn.jsdelivr.net/npm/slideout@1.0.1/dist/slideout.min.js" integrity="sha256-t+zJ/g8/KXIJMjSVQdnibt4dlaDxc9zXr/9oNPeWqdg=" crossorigin="anonymous"></script>'
    fancyboxJS = '<script src="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.js" integrity="sha256-XVLffZaxoWfGUEbdzuLi7pwaUJv1cecsQJQqGLe7axY=" crossorigin="anonymous"></script>'
    fancyboxCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.1.20/dist/jquery.fancybox.min.css" integrity="sha256-7TyXnr2YU040zfSP+rEcz29ggW4j56/ujTPwjMzyqFY=" crossorigin="anonymous">'
    timeagoJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.min.js" integrity="sha256-jwCP0NAdCBloaIWTWHmW4i3snUNMHUNO+jr9rYd2iOI=" crossorigin="anonymous"></script>'
    timeagoLocalesJS = '<script src="https://cdn.jsdelivr.net/npm/timeago.js@3.0.2/dist/timeago.locales.min.js" integrity="sha256-ZwofwC1Lf/faQCzN7nZtfijVV6hSwxjQMwXL4gn9qU8=" crossorigin="anonymous"></script>'
    flowchartDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/raphael@2.2.7/raphael.min.js" integrity="sha256-67By+NpOtm9ka1R6xpUefeGOY8kWWHHRAKlvaTJ7ONI=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/flowchart.js@1.8.0/release/flowchart.min.js" integrity="sha256-zNGWjubXoY6rb5MnmpBNefO0RgoVYfle9p0tvOQM+6k=" crossorigin="anonymous"></script>'
    sequenceDiagramsCSS = '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.css" integrity="sha384-6QbLKJMz5dS3adWSeINZe74uSydBGFbnzaAYmp+tKyq60S7H2p6V7g1TysM5lAaF" crossorigin="anonymous">'
    sequenceDiagramsJS = '<script src="https://cdn.jsdelivr.net/npm/webfontloader@1.6.28/webfontloader.js" integrity="sha256-4O4pS1SH31ZqrSO2A/2QJTVjTPqVe+jnYgOWUVr7EEc=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/snapsvg@0.5.1/dist/snap.svg-min.js" integrity="sha256-oI+elz+sIm+jpn8F/qEspKoKveTc5uKeFHNNVexe6d8=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/npm/underscore@1.8.3/underscore-min.js" integrity="sha256-obZACiHd7gkOk9iIL/pimWMTJ4W/pBsKu+oZnSeBIek=" crossorigin="anonymous"></script> <script src="https://cdn.jsdelivr.net/gh/bramp/js-sequence-diagrams@2.0.1/dist/sequence-diagram-min.js" integrity="sha384-8748Vn52gHJYJI0XEuPB2QlPVNUkJlJn9tHqKec6J3q2r9l8fvRxrgn/E5ZHV0sP" crossorigin="anonymous"></script>'

  # Display a message at the beginning of an article to warn the readers that it's content may be outdated.
  [params.outdatedInfoWarning]
    enable = false
    # Display hint if the last modified time is more than these days ago.
    hint = 30
    # Display warning if the last modified time is more than these days ago.
    warn = 180

  # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
  [params.gitment]
    # Your GitHub ID
    owner = ""
    # The repo to store comments
    repo = ""
    # Your client ID
    clientId = ""
    # Your client secret
    clientSecret = ""

  # https://utteranc.es/
  [params.utterances]
    # Your GitHub ID
    owner = ""
    # The repo to store comments
    repo = ""

  # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
  [params.gitalk]
    # Your GitHub ID
    owner = ""
    # The repo to store comments
    repo = ""
    # Your client ID
    clientId = ""
    # Your client secret
    clientSecret = ""

  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [params.valine]
    enable = false
    appId = 'appId'
    appKey = 'appKey'
    # mail notifier , https://github.com/xCss/Valine/wiki
    notify = false
    # Verification code
    verify = false
    avatar = 'mm'
    placeholder = ''
    visitor = false

  # see https://blog.olowolo.com/example-site/post/js-flowchart-diagrams/
  [params.flowchartDiagrams]
    enable = false
    options = ""

  # see https://blog.olowolo.com/example-site/post/js-sequence-diagrams/
  [params.sequenceDiagrams]
    enable = false
    # default: "{theme: 'simple'}"
    options = ""

  # count web traffic by busuanzi
  [params.busuanzi]
    enable = false
    siteUV = true
    sitePV = true
    pagePV = true

  [params.reward]
    enable = false
    wechat = "/path/to/your/wechat-qr-code.png"
    alipay = "/path/to/your/alipay-qr-code.png"

  [params.social]
    # a-email = "syun.asai@email.com"
    # b-stack-overflow = "http://localhost:1313"
    # c-twitter = "http://localhost:1313"
    # d-facebook = "http://localhost:1313"
    # e-linkedin = "http://localhost:1313"
    # f-google = "http://localhost:1313"
    g-github = "http://github.com/five-dots/"
    # h-weibo = "http://localhost:1313"
    # i-zhihu = "http://localhost:1313"
    # j-douban = "http://localhost:1313"
    # k-pocket = "http://localhost:1313"
    # l-tumblr = "http://localhost:1313"
    # m-instagram = "http://localhost:1313"
    # n-gitlab = "http://localhost:1313"
    # o-bilibili = "http://localhost:1313"

# See https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true      # 12.214.31.144 -> 12.214.31.0
  [privacy.youtube]
    privacyEnhanced = true

# Uncomment these options to make hugo output .md files.
#[mediaTypes]
#  [mediaTypes."text/plain"]
#    suffixes = ["md"]
#
#[outputFormats.MarkDown]
#  mediaType = "text/plain"
#  isPlainText = true
#  isHTML = false
#
#[outputs]
#  home = ["HTML", "RSS"]
#  page = ["HTML", "MarkDown"]
#  section = ["HTML", "RSS"]
#  taxonomy = ["HTML", "RSS"]
#  taxonomyTerm = ["HTML"]
