baseurl = "./"
title = "Hugo Onyx Theme"
theme = "hugo-onyx-theme"
enableGitInfo = true
disableFastRender = true        # Hugo 0.30

pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true

[Author]
  name = "five-dots"

[params]
  name = "five-dots"
  description = "Statistics, finance and programming."

  # Go date formats: https://golang.org/pkg/time/#pkg-constants
  dateform = "Jan 2, 2006"

  github_user = "five-dots"
  github_repo = "hugo-onyx-theme"
  github_banner = true

  # images = ["/favicon-196x196.png"] # Used in twitter_cards.html partial

  custom_css = [ # Chroma GitHub theme
                 "css/github_chroma.css" # Needs pygmentsUseClasses to be true
               ]
  custom_css_absolute = [ # Iosevka fonts
                          # "https://cdn.rawgit.com/kaushalmodi/iosevka-mirror/v1.13.2/iosevka.css"
                        ]
  custom_js  = []

  # favicon = "favicon.ico"

[params.sidebar]
  logo = "favicon.ico"

  github_button  = true
  travis_button  = false
  codecov_button = false
  gratipay = ""

  # Mon Sep 04 23:55:36 EDT 2017 - kmodi
  # Disable this option for now.. but seems to be useful in future
  show_relations = false

[params.footer]
  copyright = ""
  show_powered_by = true
